function confirmName() {
     const name = document.getElementById("name").value;

     const animals = {
       mammals: [
         "Harimau",
         "Gajah",
         "Kucing",
         "Anjing",
         "Kuda",
         "Singa",
         "Kelinci",
         "Kambing",
         "Kera",
         "Panda",
         "Koala",
         "Rusa",
         "Serigala",
         "Badak",
         "Unta",
         "Zebra",
         "Beruang",
         "Domba",
         "Lumba-lumba",
         "Gorila",
         "Simpanse",
         "Orangutan",
         "Kangguru",
         "Platipus",
         "Manusia",
         "Cheetah",
         "Leopard",
         "Puma",
         "Jaguar",
         "Gnu",
         "Bison",
         "Kerbau",
         "Hamster",
         "Marmut",
         "Tikus",
         "Tupai",
         "Berang-berang",
         "Rakuna",
         "Musang",
         "Ferret",
         "Luwak",
         "Panda Merah",
         "Walrus",
         "Anjing Laut",
         "Gajah Laut",
         "Kelinci Angora",
         "Chinchilla",
         "Kapibara",
         "Lemur",
         "Tenrec",
         "Mongoose",
         "Fossa",
         "Coatimundi",
         "Babirusa",
         "Tapir",
         "Pangolin",
         "Tarsius",
         "Vervet",
         "Gibbon",
         "Bonobo",
         "Kinkajou",
         "Margay",
         "Ocelot",
         "Caracal",
         "Serval",
         "Lynx",
         "Jaguarundi",
         "Singa Gunung",
         "Aye-aye",
         "Hedgehog",
         "Armadillo",
         "Sloth",
         "Trenggiling",
         "Manatee",
         "Dugong",
         "Narwhal",
         "Beluga",
         "Orca",
         "Paus Biru",
         "Paus Bungkuk",
         "Paus Sperma",
         "Paus Pembunuh",
         "Kangaroo Tree",
         "Wallaby",
         "Koala Bear",
         "Tasmanian Devil",
         "Bandicoot",
         "Numbat",
         "Quokka",
         "Thylacine",
         "Dingo",
         "Tasmanian Tiger",
         "Wombat",
         "Sugar Glider",
         "Mole",
         "Shrew",
         "Bat",
         "Flying Fox",
       ],
       insects: [
         "Kupu-kupu",
         "Kumbang",
         "Lalat",
         "Nyamuk",
         "Lebah",
         "Semut",
         "Jangkrik",
         "Belalang",
         "Capung",
         "Tawon",
         "Rayap",
         "Kepik",
         "Tonggeret",
         "Ngengat",
         "Kutu",
         "Kecoa",
         "Laba-laba",
         "Kumbang Badak",
         "Belalang Sembah",
         "Kumbang Tanduk",
         "Kumbang Kelapa",
         "Kumbang Gergaji",
         "Belalang Hijau",
         "Belalang Kembang",
         "Jangkrik Rumah",
         "Jangkrik Batu",
         "Jangkrik Daun",
         "Kepik Merah",
         "Kepik Hitam",
         "Kepik Coklat",
         "Kepik Oranye",
         "Capung Jarum",
         "Capung Air",
         "Capung Kepala Hijau",
         "Kumbang Kayu",
         "Kumbang Bambu",
         "Laba-laba Jaring",
         "Laba-laba Kuning",
         "Laba-laba Merah",
         "Laba-laba Hitam",
         "Semut Merah",
         "Semut Hitam",
         "Semut Api",
         "Semut Kayu",
         "Semut Daun",
         "Semut Gula",
         "Lebah Madu",
         "Lebah Penjaga",
         "Lebah Tukang Kayu",
         "Lebah Kerdil",
         "Lebah Ratu",
         "Lebah Pekerja",
         "Lalat Buah",
         "Lalat Rumah",
         "Lalat Daging",
         "Lalat Pasir",
         "Lalat Tsetse",
         "Nyamuk Anopheles",
         "Nyamuk Aedes",
         "Nyamuk Culex",
         "Ngengat Sutra",
         "Ngengat Malam",
         "Ngengat Kain",
         "Ngengat Daun",
         "Ngengat Tanah",
         "Kutu Kepala",
         "Kutu Tubuh",
         "Kutu Rambut",
         "Kutu Kasur",
         "Kutu Anjing",
         "Kutu Kucing",
         "Kutu Burung",
         "Jangkrik Laut",
         "Jangkrik Pasir",
         "Jangkrik Hutan",
         "Belalang Tempurung",
         "Belalang Bambu",
         "Belalang Sawah",
         "Belalang Padang Rumput",
         "Belalang Kaktus",
         "Capung Liar",
         "Capung Pantai",
         "Capung Rawa",
         "Kepik Tanah",
         "Kepik Hutan",
         "Kepik Air",
         "Kepik Terbang",
         "Kumbang Tanah",
         "Kumbang Air",
         "Kumbang Terbang",
         "Kumbang Bumi",
         "Kumbang Daun",
         "Kumbang Kotoran",
       ],
       birds: [
         "Elang",
         "Merpati",
         "Burung Gereja",
         "Burung Beo",
         "Kakatua",
         "Nuri",
         "Kakatua Hitam",
         "Burung Hantu",
         "Rajawali",
         "Alap-alap",
         "Pipit",
         "Sikatan",
         "Cendet",
         "Burung Kuntul",
         "Bangau",
         "Flamingo",
         "Pelikan",
         "Angsa",
         "Bebek",
         "Gagak",
         "Raven",
         "Burung Hitam",
         "Burung Emas",
         "Kenari",
         "Puyuh",
         "Ayam",
         "Burung Merak",
         "Burung Jalak",
         "Burung Kolibri",
         "Burung Pipit",
         "Camar",
         "Burung Kecil",
         "Perkutut",
         "Burung Dara",
         "Burung Kedasih",
         "Burung Robin",
         "Burung Layang-layang",
         "Burung Sriti",
         "Burung Elang Laut",
         "Burung Dodo",
         "Burung Kiwi",
         "Burung Unta",
         "Burung Kasuari",
         "Burung Emu",
         "Burung Beo Nuri",
         "Burung Kakaktua Kecil",
         "Burung Tekukur",
         "Burung Betet",
         "Burung Kacamata",
         "Burung Kapinis",
         "Burung Cenderawasih",
         "Burung Bangau Hitam",
         "Burung Tengkek",
         "Burung Kedidi",
         "Burung Kuntul Hitam",
         "Burung Bubut",
         "Burung Cikalang",
         "Burung Kuntul Kecil",
         "Burung Mandar",
         "Burung Pecuk",
         "Burung Kasuari Kecil",
         "Burung Gagak Hitam",
         "Burung Manyar",
         "Burung Kuntul Besar",
         "Burung Walet",
         "Burung Kolibri Merah",
         "Burung Pelatuk",
         "Burung Kutilang",
         "Burung Cucakrowo",
         "Burung Jalak Bali",
         "Burung Jalak Suren",
         "Burung Murai",
         "Burung Trulek",
         "Burung Cenderawasih Kuning",
         "Burung Pipit Padi",
         "Burung Madu",
         "Burung Tekukur Jawa",
         "Burung Kutilang Emas",
         "Burung Wren",
         "Burung Finch",
         "Burung Remetuk",
         "Burung Perling",
         "Burung Kekep",
         "Burung Sepah",
         "Burung Alap-alap Borneo",
         "Burung Bondol",
         "Burung Kadalan",
         "Burung Trocero",
         "Burung Seriwang",
         "Burung Alap-alap Jepang",
         "Burung Kuntul Karang",
         "Burung Cucak Hijau",
         "Burung Kacer",
         "Burung Cililin",
         "Burung Branjangan",
         "Burung Gelatik",
       ],
       reptiles: [
         "Kadal",
         "Bunglon",
         "Iguana",
         "Tokek",
         "Komodo",
         "Buaya",
         "Aligator",
         "Tuatara",
         "Anaconda",
         "Python",
         "Ular Piton",
         "Ular Kobra",
         "Ular Derik",
         "Ular Sanca",
         "Ular Laut",
         "Ular Boa",
         "Ular Pelangi",
         "Ular Rattlesnake",
         "Ular Viper",
         "Ular Mamba",
         "Ular Hijau",
         "Ular Coklat",
         "Ular Garter",
         "Ular Karpet",
         "Ular Sawah",
         "Ular Terbang",
         "Ular Ekor Merah",
         "Ular Rawa",
         "Kura-kura",
         "Penyu",
         "Tuntong",
         "Kura-kura Leher Panjang",
         "Kura-kura Leher Pendek",
         "Kura-kura Box",
         "Kura-kura Kayu",
         "Kura-kura Gading",
         "Kura-kura Emas",
         "Kura-kura Matahari",
         "Penyu Hijau",
         "Penyu Belimbing",
         "Penyu Sisik",
         "Penyu Pipih",
         "Penyu Lekang",
         "Kura-kura Galapagos",
         "Kura-kura Raksasa",
         "Kura-kura Labi-labi",
         "Kura-kura Duri",
         "Kura-kura Florida",
         "Kura-kura Gurun",
         "Kura-kura China",
         "Kura-kura Afrika",
         "Kura-kura Amerika",
         "Kura-kura Asia",
         "Kura-kura Eropa",
         "Kura-kura Indonesia",
         "Bunglon Veiled",
         "Bunglon Panther",
         "Bunglon Jackson",
         "Bunglon Meller",
         "Bunglon Parson",
         "Bunglon Carpet",
         "Bunglon Fischer",
         "Bunglon Lygodactylus",
         "Bunglon Brookesia",
         "Bunglon Pygmy",
         "Iguana Hijau",
         "Iguana Hitam",
         "Iguana Ekor Cincin",
         "Iguana Laut",
         "Iguana Darat",
         "Iguana Hutan",
         "Iguana Gurun",
         "Iguana Pulau",
         "Iguana Karibia",
         "Iguana Cayman",
         "Iguana Haiti",
         "Iguana Spanyol",
         "Iguana Amerika Tengah",
         "Iguana Amerika Selatan",
         "Iguana Filipina",
         "Iguana Sulawesi",
         "Iguana Papua",
         "Iguana Queensland",
         "Iguana New Guinea",
         "Iguana Pulau Galapagos",
         "Komodo Dragon",
         "Komodo Flores",
         "Komodo Rinca",
         "Komodo Padar",
         "Komodo Gili Motang",
         "Komodo Gunung",
         "Komodo Dataran",
         "Komodo Laut",
         "Komodo Pasir",
       ],
       amphibians: [
         "Katak",
         "Kodok",
         "Salamander",
         "Axolotl",
         "Caecilian",
         "Salamander Harimau",
         "Salamander Raksasa",
         "Salamander Biru",
         "Salamander Berapi",
         "Salamander Spotted",
         "Salamander Hidung Panjang",
         "Salamander Gila",
         "Salamander Mudpuppy",
         "Salamander Nerpa",
         "Salamander Merah",
         "Salamander Coklat",
         "Salamander Kuning",
         "Salamander Hijau",
         "Salamander Orange",
         "Salamander Hitam",
         "Katak Emas",
         "Katak Daun",
         "Katak Pohon",
         "Katak Merah",
         "Katak Hijau",
         "Katak Biru",
         "Katak Kaca",
         "Katak Kerdil",
         "Katak Raksasa",
         "Katak Api",
         "Katak Pelangi",
         "Katak Penyu",
         "Katak Kumbang",
         "Katak Gila",
         "Katak Kepala Kucing",
         "Katak Kayu",
         "Katak Jepang",
         "Katak Afrika",
         "Katak Australia",
         "Katak Asia",
         "Katak Amerika",
         "Katak Amerika Selatan",
         "Katak Filipina",
         "Katak Indonesia",
         "Katak Sulawesi",
         "Katak Papua",
         "Katak Queensland",
         "Katak New Guinea",
         "Katak Pulau",
         "Katak Gunung",
         "Katak Dataran",
         "Kodok Tebu",
         "Kodok Bufo",
         "Kodok Amerika",
         "Kodok Hijau",
         "Kodok Eropa",
         "Kodok Spadefoot",
         "Kodok Kalimantan",
         "Kodok Jawa",
         "Kodok Sumatra",
         "Kodok Bali",
         "Kodok Madagaskar",
         "Kodok Meksiko",
         "Kodok Amazon",
         "Kodok Cina",
         "Kodok Jepang",
         "Kodok Korea",
         "Kodok Vietnam",
         "Kodok Thailand",
         "Kodok India",
         "Kodok Nepal",
         "Kodok Bhutan",
         "Kodok Sri Lanka",
         "Kodok Malaysia",
         "Kodok Singapura",
         "Kodok Myanmar",
         "Kodok Laos",
         "Kodok Kamboja",
         "Kodok Filipina",
         "Kodok Brunei",
         "Kodok Timor Leste",
         "Kodok Bangladesh",
         "Kodok Pakistan",
         "Kodok Afghanistan",
         "Kodok Iran",
         "Kodok Irak",
         "Kodok Turki",
         "Kodok Suriah",
         "Kodok Yordania",
         "Kodok Israel",
         "Kodok Lebanon",
         "Kodok Mesir",
         "Kodok Sudan",
         "Kodok Libya",
         "Kodok Tunisia",
         "Kodok Aljazair",
         "Kodok Maroko",
         "Kodok Mauritania",
       ],
       fish: [
         "Ikan Mas",
         "Ikan Koi",
         "Ikan Cupang",
         "Ikan Guppy",
         "Ikan Arwana",
         "Ikan Louhan",
         "Ikan Discus",
         "Ikan Molly",
         "Ikan Neon Tetra",
         "Ikan Zebra",
         "Ikan Oscar",
         "Ikan Badut",
         "Ikan Sapu-sapu",
         "Ikan Komet",
         "Ikan Buntal",
         "Ikan Gabus",
         "Ikan Sepat",
         "Ikan Baronang",
         "Ikan Tenggiri",
         "Ikan Patin",
         "Ikan Lele",
         "Ikan Gurame",
         "Ikan Bandeng",
         "Ikan Tongkol",
         "Ikan Kembung",
         "Ikan Tuna",
         "Ikan Salmon",
         "Ikan Kakap",
         "Ikan Baronang Susu",
         "Ikan Hiu",
         "Ikan Paus",
         "Ikan Pari",
         "Ikan Gindara",
         "Ikan Baronang Batu",
         "Ikan Layur",
         "Ikan Sarden",
         "Ikan Makarel",
         "Ikan Kakap Merah",
         "Ikan Kerapu",
         "Ikan Lencam",
         "Ikan Belida",
         "Ikan Mujair",
         "Ikan Nila",
         "Ikan Patin Jambal",
         "Ikan Sidat",
         "Ikan Baramundi",
         "Ikan Belanak",
         "Ikan Tenggiri Batang",
         "Ikan Tenggiri Papan",
         "Ikan Tenggiri Papan Besar",
         "Ikan Tenggiri Papan Kecil",
         "Ikan Tenggiri Padang",
         "Ikan Tenggiri Bunga",
         "Ikan Tenggiri Gigi",
         "Ikan Tenggiri Kuning",
         "Ikan Tenggiri Mas",
         "Ikan Tenggiri Hitam",
         "Ikan Tenggiri Merah",
         "Ikan Tenggiri Biru",
         "Ikan Tenggiri Putih",
         "Ikan Tenggiri Abu-abu",
         "Ikan Tenggiri Hijau",
         "Ikan Tenggiri Coklat",
         "Ikan Tenggiri Orange",
         "Ikan Tenggiri Pink",
         "Ikan Tenggiri Ungu",
         "Ikan Tenggiri Transparan",
         "Ikan Tenggiri Cerah",
         "Ikan Tenggiri Gelap",
         "Ikan Tenggiri Berbintik",
         "Ikan Tenggiri Bergaris",
         "Ikan Tenggiri Belang",
         "Ikan Tenggiri Besar",
         "Ikan Tenggiri Kecil",
         "Ikan Tenggiri Panjang",
         "Ikan Tenggiri Pendek",
         "Ikan Tenggiri Pipih",
         "Ikan Tenggiri Bulat",
         "Ikan Tenggiri Lonjong",
         "Ikan Tenggiri Oval",
         "Ikan Tenggiri Segitiga",
         "Ikan Tenggiri Kotak",
         "Ikan Tenggiri Silinder",
         "Ikan Tenggiri Tabung",
         "Ikan Tenggiri Batang Besar",
         "Ikan Tenggiri Batang Kecil",
         "Ikan Tenggiri Batang Panjang",
         "Ikan Tenggiri Batang Pendek",
         "Ikan Tenggiri Batang Pipih",
         "Ikan Tenggiri Batang Bulat",
         "Ikan Tenggiri Batang Lonjong",
         "Ikan Tenggiri Batang Oval",
         "Ikan Tenggiri Batang Segitiga",
         "Ikan Tenggiri Batang Kotak",
         "Ikan Tenggiri Batang Silinder",
         "Ikan Tenggiri Batang Tabung",
       ],
     };

     const categories = [
       "mammals",
       "insects",
       "birds",
       "reptiles",
       "amphibians",
       "fish",
     ];
     const randomCategory =
       categories[Math.floor(Math.random() * categories.length)];
     const randomAnimal =
       animals[randomCategory][
         Math.floor(Math.random() * animals[randomCategory].length)
       ];

     const result = `Khodam ${name} adalah ${randomAnimal}`;
     document.getElementById("result").textContent = result;
   }

   function resetForm() {
     document.getElementById("nameForm").reset();
     document.getElementById("result").textContent = "";
   }